<?php require 'header.html' ?>
<?php require 'nav.html' ?>
<?php require 'landing.html' ?>
<?php require 'carousel1.html' ?>
<?php require 'carousel2.html' ?>
<?php require 'carousel3.html' ?>
<?php require 'carousel4.html' ?>
<?php require 'carousel5.html' ?>
<?php require 'contact.html' ?>
<?php require 'footer.html' ?>
<?php require 'scripts.html' ?>